export const menu = [
  {
    id: 1,
    category: "Beverages",
    emoji: "☕",
    items: [
      { name: "Pop/Soda", price: 2.00, img: '/stmark-festival-menu/images/MB Pop.jpg', imgFit: 'contain' },
      { name: "Bottled Water", price: 2.00, img: '/stmark-festival-menu/images/MB Water.jpg', imgFit: 'contain' },
      { name: "Lemonade", price: 5.00, img: '/stmark-festival-menu/images/MB Lemonade.jpg', imgFit: 'contain' },
      {
        name: "Fruit Smoothie",
        price: 7.00,
        desc: "Bananas, mangos, strawberries, honey",
        img: '',
      },
      { name: "Sugar Cane Fresh Juice", price: 7.00, img: '' },
      {
        name: "Egyptian Dates with Milk",
        price: 7.00,
        desc: "Naturally sweet dates blended into rich, chilled milk. Pure, creamy comfort in every sip.",
        img: '/stmark-festival-menu/images/MB dates with milk.webp',
      },
      {
        name: "Mango Drink",
        price: 7.00,
        desc: "Packed with fresh, ripe mangoes for a rich flavor",
        img: '/stmark-festival-menu/images/MB Mango drink.jpeg',
      },
      {
        name: "Hibiscus",
        suffix: "(Karkadeh)",
        price: 5.00,
        desc: "A refreshing, sweet, and tart deep-red iced tea",
        img: '/stmark-festival-menu/images/MB Hibiscus.jpg',
      },
      {
        name: "Kharoub",
        price: 5.00,
        desc: "A traditional, naturally sweet, and earthy chilled cold brewed Carob",
        img: '/stmark-festival-menu/images/MB Kharoub (1).jpeg',
      },
      {
        name: "Sobia",
        price: 7.00,
        desc: "A creamy, sweet, and icy coconut-flavored drink",
        img: '/stmark-festival-menu/images/MB coconut-sobia-juice.jpg',
      },
      {
        name: "Tamarind",
        suffix: "(Tamr Hindi)",
        price: 5.00,
        desc: "A tangy, sweet, and deeply refreshing classic summer beverage.",
        img: '/stmark-festival-menu/images/MB tamr hindi.jpeg',
      },
      { name: "Egyptian Coffee", suffix: "Sold in Social Hall", price: 3.00, img: '/stmark-festival-menu/images/DSC00432.JPG' },
      { name: "American Coffee", suffix: "Sold in Social Hall", price: 2.50, img: '' },
      { name: "Tea Selection", suffix: "Sold in Social Hall", price: 2.50, img: '' },
    ],
  },
  {
    id: 2,
    category: "À La Carte",
    emoji: "🫓",
    items: [
      {
        name: "Egyptian Macaroni Béchamel",
        price: 8.00,
        desc: "Baked penne pasta layered with seasoned minced beef and a creamy, golden béchamel sauce.",
        img: '/stmark-festival-menu/images/MB Egyptian-Macarona-Bechamel.jpg',
      },
      {
        name: "Kobeba",
        suffix: "(1 piece)",
        price: 4.00,
        desc: "A crispy, fried bulgur wheat shell stuffed with savory spiced minced beef and onions.",
        img: '/stmark-festival-menu/images/MB kobeba3.jpg',
      },
      {
        name: "Stuffed Grape Leaves",
        suffix: "(5 pieces)",
        price: 6.00,
        img: '/stmark-festival-menu/images/MB grape-leaves_0.jpg',
      },
      {
        name: "Spinach Sambousek",
        suffix: "(1 piece)",
        price: 3.00,
        desc: "A crispy, golden pastry filled with seasoned spinach.",
        img: '/stmark-festival-menu/images/MB Spinach Sambousek.jpg',
      },
      {
        name: "Cheese Sambousek",
        suffix: "(1 piece)",
        price: 3.00,
        desc: "A flaky and savory pastry pocket packed with a warm cheese blend.",
        img: '/stmark-festival-menu/images/MB Cheese Sambousek.jpg',
      },
    ],
  },
  {
    id: 3,
    category: "Vegetarian",
    emoji: "🥗",
    items: [
      {
        name: "Falafel Sandwich",
        price: 9.00,
        desc: "Crispy Egyptian fava bean falafels tucked into warm bread with fresh veggies and tahini.",
        img: '/stmark-festival-menu/images/MB falafel sandwich.jpg',
      },
      { name: "Falafel", suffix: "(3 pieces)", price: 6.00, img: '' },
      {
        name: "Koshari Platter",
        price: 10.00,
        desc: "Egypt's ultimate street food—a hearty mix of rice, macaroni, lentils, and chickpeas, topped with spicy tomato sauce and crispy onions.",
        img: '',
      },
      {
        name: "Tabouli Salad",
        price: 6.00,
        desc: "A bright, refreshing salad of finely chopped parsley, tomatoes, and bulgur wheat in a lemon-olive oil dressing.",
        img: '/stmark-festival-menu/images/MB tabouli.jpeg',
      },
      {
        name: "Grilled Corn on the Cob",
        suffix: "(1 piece)",
        price: 2.00,
        img: '/stmark-festival-menu/images/markusphotographyllc-748.jpg',
      },
      {
        name: "Baba Ghanoush",
        price: 5.00,
        desc: "A smoky, creamy roasted eggplant dip blended with tahini and garlic.",
        img: '/stmark-festival-menu/images/MB Baba Ghanoush.jpg',
      },
      { name: "Tahini", price: 3.00, img: '' },
      { name: "French Fries", price: 4.00, img: '/stmark-festival-menu/images/MB french fries.jpg' },
      { name: "Funnel Cake", price: 7.00, img: '/stmark-festival-menu/images/MB funnel cake.jpg' },
    ],
  },
  {
    id: 4,
    category: "Signature Platters",
    emoji: "🍽️",
    items: [
      {
        name: "Lamb Shank",
        price: 20.00,
        desc: "Tender, fall-off-the-bone slow-roasted lamb shank in a rich savory tomato sauce. Served with vermicelli rice and corn.",
        img: '/stmark-festival-menu/images/MB lamb shank 3.jpg',
      },
      {
        name: "Three Meat Variety",
        price: 18.00,
        desc: "The ultimate grill platter featuring a skewer of Shish Kabob, Chicken Shish, and Kofta. Served with vermicelli rice and corn.",
        img: '',
      },
      {
        name: "Lamb Shish Kabob",
        suffix: "(2 skewers)",
        price: 17.00,
        desc: "Tender cubes of marinated lamb grilled to perfection on skewers. Served with vermicelli rice and corn.",
        img: '/stmark-festival-menu/images/MB kabob.jpg',
      },
      {
        name: "Chicken Shish",
        suffix: "(4 tenders)",
        price: 15.00,
        desc: "Juicy, marinated grilled chicken tenders loaded with flavor. Served with vermicelli rice and corn.",
        img: '/stmark-festival-menu/images/MB chicken shish.jpg',
      },
      {
        name: "Kofta",
        suffix: "(3 pieces)",
        price: 15.00,
        desc: "Char-grilled skewers of perfectly seasoned minced meat. Served with vermicelli rice and corn.",
        img: '/stmark-festival-menu/images/MB kofta platter.jpg',
      },
      {
        name: "Egyptian Grilled Lamb Chops",
        suffix: "(3 chops)",
        price: 18.00,
        desc: "Tender lamb chops marinated in traditional herbs and flame-grilled. Served with vermicelli rice and corn.",
        img: '',
      },
    ],
  },
  {
    id: 5,
    category: "Desserts",
    emoji: "🍮",
    items: [
      {
        name: "Om Ali",
        price: 7.00,
        desc: "Egyptian bread pudding with nuts, raisins, coconut and cream.",
        img: '',
      },
      {
        name: "Basbousa",
        price: 5.00,
        desc: "Semolina cake soaked in rose water syrup, topped with almonds.",
        img: '',
      },
      {
        name: "Kunafa",
        price: 6.00,
        desc: "Shredded wheat pastry filled with sweet cheese, soaked in syrup.",
        img: '',
      },
      {
        name: "Baklava",
        suffix: "(2 pieces)",
        price: 4.00,
        desc: "Layers of crispy filo pastry filled with chopped nuts and honey syrup.",
        img: '',
      },
    ],
  },
  {
    id: 6,
    category: "Egyptian Specials",
    emoji: "🌟",
    items: [
      {
        name: "Hawawshi",
        price: 12.00,
        desc: "A crispy freshly baked Egyptian bread stuffed with a spiced, savory minced beef filling with special spices.",
        img: '/stmark-festival-menu/images/MB Hawawshi.jpg',
      },
      {
        name: "Egyptian Fresh Bread",
        suffix: "(1 loaf)",
        price: 1.50,
        img: '/stmark-festival-menu/images/MB Egyptian Fresh Bread.jpg',
      },
    ],
  },
  {
    id: 7,
    category: "Kids Corner",
    emoji: "🎈",
    items: [
      {
        name: "Cheeseburger Happy Meal",
        price: 7.00,
        desc: "Burger sandwich, fries, and juice",
        img: '',
      },
      {
        name: "Chicken Nuggets Happy Meal",
        price: 7.00,
        desc: "5 chicken nuggets, fries, and juice",
        img: '',
      },
      {
        name: "Beef Hotdog Sandwich Happy Meal",
        price: 7.00,
        desc: "1 sandwich, fries, and juice",
        img: '',
      },
      { name: "Kettle Popcorn", price: 2.00, img: '' },
      { name: "Cotton Candy", price: 2.00, img: '' },
      { name: "Gourmet Waffle Sticks", price: 6.00, img: '' },
      { name: "Dubai Chocolate", price: 6.00, img: '' },
      { name: "Ice Cream", price: 3.00, img: '' },
      { name: "ICEE", price: 1.00, img: '' },
      { name: "Chocolate Covered Oreo or Pretzel", price: 2.00, img: '' },
      { name: "Chocolate Covered Pretzel", price: 2.00, img: '' },
      { name: "Iced Coffee", price: 3.00, img: '' },
      { name: "Iced Latte", price: 5.00, img: '' },
    ],
  },
  {
    id: 8,
    category: "Sandwiches & Feteer",
    emoji: "🥙",
    items: [
      { name: "Chicken Shawarma", price: 12.00, img: '' },
      {
        name: "Egyptian Beef Shawarma",
        price: 12.00,
        desc: "Tender, seasoned strips of beef with tahini and onions wrapped in fresh bread.",
        img: '/stmark-festival-menu/images/MB beef shawerma.jpg',
      },
      {
        name: "Gyro",
        suffix: "(Meat)",
        price: 12.00,
        desc: "Seasoned rotisserie meat served with fresh tzatziki and veggies in a pita.",
        img: '',
      },
      {
        name: "Kofta",
        price: 12.00,
        desc: "Grilled, seasoned minced meat wrapped with tahini and fresh greens.",
        img: '/stmark-festival-menu/images/MB kofta sandwich.jpg',
      },
      {
        name: "Beef Liver",
        suffix: "(Alexandrian Style)",
        price: 12.00,
        desc: "Pan-seared beef liver cooked with garlic, green peppers, and traditional Alexandrian spices (optional: Jalapeño)",
        img: '/stmark-festival-menu/images/MB liver Sandwich.jpg',
      },
      {
        name: "Egyptian Sausage",
        price: 12.00,
        desc: "Savory, zesty Egyptian beef sausage sautéed with peppers, onions, and tomatoes. (optional: Jalapeño)",
        img: '/stmark-festival-menu/images/MB Egyptian sausage.webp',
      },
      {
        name: "Feteer Meshaltet",
        suffix: "(Plain)",
        price: 25.00,
        desc: "A traditional Egyptian pastry—golden, buttery, and baked into crispy, flaky layers.",
        img: '/stmark-festival-menu/images/MB feteer.jpg',
      },
      {
        name: "Feteer Meshaltet",
        suffix: "(Powdered Sugar)",
        price: 25.00,
        desc: "A traditional Egyptian pastry—golden, buttery, and baked into crispy, flaky layers.",
        img: '',
      },
      {
        name: "Feteer Meshaltet",
        suffix: "(Stuffed)",
        price: 35.00,
        desc: "Stuffed with your choice of: Egyptian Sausage, Aromatic Cured Beef (Basterma), or Cheese Blend.",
        img: '/stmark-festival-menu/images/MB Stuffed Savory.jpg',
      },
      {
        name: "Add Mish",
        desc: "Upgrade your pastry with a side of sharp, salty, and traditional Egyptian aged cheese",
        price: 7.00,
        img: '',
      },
      {
        name: "Add Nutella Side",
        desc: "Sweet finish to give a twist to your warm, buttery layers",
        price: 5.00,
        img: '',
      },
    ],
  },
];
