export const menu = [
  {
    id: 1,
    category: "Beverages",
    emoji: "☕",
    items: [
      { name: "Pop/Soda", price: 2.00, img: '' },
      { name: "Bottled Water", price: 2.00, img: '' },
      { name: "Lemonade", price: 5.00, img: '' },
      {
        name: "Fruit Smoothie",
        price: 7.00,
        desc: "Bananas, mangos, strawberries, honey",
        img: '',
      },
      { name: "Sugar Cane Fresh Juice", price: 7.00, img: '/stmark-festival-menu/images/DSC_0123.JPG' },
      {
        name: "Hibiscus",
        price: 5.00,
        desc: "Hibiscus, water, little sugar",
        img: '',
      },
      {
        name: "Kharoub",
        price: 5.00,
        desc: "Cold brewed Carob pods, sweet and refreshing",
        img: '',
      },
      { name: "American or Egyptian Coffee", price: 2.50, img: '/stmark-festival-menu/images/DSC00432.JPG' },
    ],
  },
  {
    id: 2,
    category: "Signature Platters",
    emoji: "🍽️",
    items: [
      {
        name: "Lamb Shank",
        price: 20.00,
        desc: "Lamb braised with special tomato sauce. Served with vermicelli rice.",
        img: '/stmark-festival-menu/images/DSC00509.JPG',
      },
      {
        name: "Three Meat Variety",
        price: 18.00,
        desc: "Shish kabob, chicken kabob and kofta. Served with vermicelli rice and corn.",
        img: '',
      },
      {
        name: "Lamb Shish Kabob",
        suffix: "(2 skewers)",
        price: 16.00,
        desc: "Tender seasoned and marinated lamb cubes grilled over charcoal, vermicelli rice and corn.",
        img: '/stmark-festival-menu/images/DSC_0097.JPG',
      },
      {
        name: "Chicken Shish Tenders/Thighs",
        suffix: "(2 skewers)",
        price: 15.00,
        desc: "Tenders/thighs seasoned and marinated chicken cubes grilled over charcoal. Served with vermicelli rice and corn.",
        img: '/stmark-festival-menu/images/chicken tender.jpg',
      },
      {
        name: "Kofta",
        suffix: "(3 pieces)",
        price: 15.00,
        desc: "Spiced ground beef & lamb, grilled over charcoal. Served with vermicelli rice and corn.",
        img: '/stmark-festival-menu/images/DSC_0026.JPG',
      },
      {
        name: "Chicken Shawarma Platter",
        price: 15.00,
        desc: "Marinated chicken, grilled and thinly sliced. Served with vermicelli rice, corn and tahini.",
        img: '/stmark-festival-menu/images/chircken shawerma.jpeg',
      },
      {
        name: "Egyptian Beef Shawarma Platter",
        price: 15.00,
        desc: "Marinated beef, grilled and thinly sliced. Served with vermicelli rice, corn and tahini.",
        img: '/stmark-festival-menu/images/DSC_0051.JPG',
      },
    ],
  },
  {
    id: 3,
    category: "Salads & Sides",
    emoji: "🥗",
    items: [
      {
        name: "Fattoush",
        price: 7.00,
        desc: "Mixed greens, tomatoes, cucumber, radishes, crispy pita chips, sumac dressing.",
        img: '/stmark-festival-menu/images/DSC00492.JPG',
      },
      {
        name: "Tahini Salad",
        price: 6.00,
        desc: "Cucumber, tomato, parsley, tahini dressing.",
        img: '',
      },
      {
        name: "Vermicelli Rice",
        price: 4.00,
        img: '/stmark-festival-menu/images/DSC00502.JPG',
      },
      {
        name: "Corn on the Cob",
        price: 3.00,
        img: '/stmark-festival-menu/images/DSC_0083.JPG',
      },
      {
        name: "Pita Bread",
        suffix: "(3 pieces)",
        price: 2.00,
        img: '',
      },
    ],
  },
  {
    id: 4,
    category: "À La Carte",
    emoji: "🫓",
    items: [
      {
        name: "Egyptian Macaroni Béchamel",
        price: 7.00,
        desc: "Penne pasta, ground beef, tomato sauce, butter, flour and milk",
        img: '/stmark-festival-menu/images/DSC00482.JPG',
      },
      {
        name: "Kobeba",
        suffix: "(1 piece)",
        price: 3.00,
        desc: "Deep fried ground beef, chopped onions, salt, pepper, cinnamon and bourghul (cracked wheat)",
        img: '/stmark-festival-menu/images/DSC00485.JPG',
      },
      {
        name: "Stuffed Grape Leaves",
        suffix: "(5 pieces)",
        price: 6.00,
        img: '/stmark-festival-menu/images/DSC00486.JPG',
      },
      {
        name: "Spinach Sambousek",
        suffix: "(1 piece)",
        price: 3.00,
        desc: "Flaky dough stuffed with spinach, butter",
        img: '/stmark-festival-menu/images/DSC00489.JPG',
      },
      {
        name: "Cheese Sambousek",
        suffix: "(1 piece)",
        price: 3.00,
        desc: "Buttery flaky dough stuffed with blue cheese, crème and feta cheese",
        img: '/stmark-festival-menu/images/cheese sambusek.jpg',
      },
    ],
  },
  {
    id: 5,
    category: "Desserts",
    emoji: "🍮",
    items: [
      {
        name: "Om Ali",
        price: 7.00,
        desc: "Egyptian bread pudding with nuts, raisins, coconut and cream.",
        img: '/stmark-festival-menu/images/DSC00416.JPG',
      },
      {
        name: "Basbousa",
        price: 5.00,
        desc: "Semolina cake soaked in rose water syrup, topped with almonds.",
        img: '/stmark-festival-menu/images/DSC_0539.JPG',
      },
      {
        name: "Kunafa",
        price: 6.00,
        desc: "Shredded wheat pastry filled with sweet cheese, soaked in syrup.",
        img: '/stmark-festival-menu/images/DSC_0109.JPG',
      },
      {
        name: "Baklava",
        suffix: "(2 pieces)",
        price: 4.00,
        desc: "Layers of crispy filo pastry filled with chopped nuts and honey syrup.",
        img: '/stmark-festival-menu/images/DSC00420.JPG',
      },
    ],
  },
  {
    id: 6,
    category: "Egyptian Specials",
    emoji: "🌟",
    items: [
      {
        name: "Hawawshi",
        price: 12.00,
        desc: "Minced meat with special spices, onions, pepper, parsley, stuffed in fresh Egyptian bread",
        img: '',
      },
      {
        name: "Egyptian Fresh Bread",
        suffix: "(1 loaf)",
        price: 1.50,
        img: '',
      },
    ],
  },
  {
    id: 7,
    category: "Sandwiches & Feteer",
    emoji: "🥙",
    items: [
      { name: "Chicken Shawarma", price: 12.00, img: '/stmark-festival-menu/images/chircken shawerma2.jpg' },
      { name: "Egyptian Beef Shawarma", price: 12.00, img: '/stmark-festival-menu/images/DSC_0134.JPG' },
      { name: "Gyro (Meat)", price: 12.00, img: '/stmark-festival-menu/images/DSC_0136.JPG' },
      { name: "Kofta", price: 12.00, img: '/stmark-festival-menu/images/DSC_0026.JPG' },
      {
        name: "Beef Liver (Alexandrian Style)",
        price: 12.00,
        desc: "Beef liver, onions, green peppers topped with tahini (optional: Jalapeño)",
        img: '/stmark-festival-menu/images/DSC00519.JPG',
      },
      { name: "Egyptian Sausage", price: 12.00, img: '/stmark-festival-menu/images/DSC_0286.JPG' },
      {
        name: "Feteer Meshaltet",
        suffix: "(plain)",
        price: 8.00,
        desc: "Traditional Egyptian layered pastry, light and flaky.",
        img: '/stmark-festival-menu/images/DSC_0144.JPG',
      },
    ],
  },
];
